version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: dev
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    environment:
      # Please select 'DevContainer'
      - RUN_ON=DevContainer

  localstack:
      container_name: localstack
      image: localstack/localstack
      ports:
        - 4566:4566
      environment:
        SERVICES: s3,dynamodb,lambda
        DATA_DIR: /tmp/localstack/data
      volumes:
        - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"
