name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1
      AWS_ACCOUNT_ID: "000000000000"
      AWS_ACCESS_KEY_ID: dummy-access-key
      AWS_SECRET_ACCESS_KEY: dummy-secret-key
    services:
      localstack:
        image: localstack/localstack:0.13.0
        env:
          SERVICES: dynamodb
          DEFAULT_REGION: ap-northeast-1
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v3
      - name: Create table and insert initial data.
        run: | 
          aws dynamodb create-table --cli-input-json file://dynamodb/users-table.json --endpoint-url http://localhost:4566
          aws dynamodb describe-table --table-name users-table --endpoint-url http://localhost:4566
          aws dynamodb put-item --item file://dynamodb/users.json --table-name users-table --endpoint-url http://localhost:4566

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Install dependencies
        run: make deps

      - name: Build
        run: make build

      # - name: Unit Test
      #   env:
      #     DEFAULT_REGION: ap-northeast-1
      #     RUN_ON: GithubActions
      #   run: go test